import React from 'react'

function SobreNosImages({
  titleOfImages,
  image1,
  image2,
  image3,
  image4,
  image5,
  image6,
  image7,
  image8,
  image9,
  image10,
  image11,
  image12,
}) {
  return (
    <>
      <div className="fourth-row-sobrenos">
        <div className="fourth-row-sobrenos-content">
          <h1>{titleOfImages}</h1>
          <div className="images-sobrenos-content">
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src="https://www.instagram.com/p/Cbh4XPmvgpP/embed"
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
          </div>
        </div>
      </div>
    </>
  )
}

export default SobreNosImages
