import React from 'react'

function SobreNosImages({
  titleOfImages,
  image1,
  image2,
  image3,
  image4,
  image5,
  image6,
  image7,
  image8,
  image9,
  image10,
  image11,
  image12,
}) {
  return (
    <>
      <div className="fourth-row-sobrenos">
        <div className="fourth-row-sobrenos-content">
          <h1>{titleOfImages}</h1>
          <div className="images-sobrenos-content">
            <iframe
              src={image1}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image2}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image3}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image4}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image5}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image6}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image7}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image8}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image9}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image10}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image11}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
            <iframe
              src={image12}
              width="166"
              height="240"
              frameborder="0"
              scrolling="no"
              allowtransparency="true"
            ></iframe>
          </div>
        </div>
      </div>
    </>
  )
}

export default SobreNosImages
